Feature/menu
mariaruncan/maria-internship-scooterapp pull request #13
Opened 2022-09-27 12:10 UTC by mariaruncan

2022-09-28 06:19 UTC, catadarjan-tapptitude requested changes

2022-09-28 06:19 UTC, catadarjan-tapptitude commented on app/src/main/res/values/styles.xml
> +    <style name="SheetDialog" parent="Theme.Design.Light.BottomSheetDialog">
I think `BottomSheetDialog` would be more appropriate

2022-09-28 06:19 UTC, catadarjan-tapptitude commented on app/src/main/java/com/internship/move/data/model/User.kt
> +            "free" -> FREE
I'd extract these strings to static fields

2022-09-28 06:19 UTC, catadarjan-tapptitude commented on app/src/main/java/com/internship/move/data/dto/UsersApiResponses.kt
> +    fun toUser(): User{
Remember to periodically format your code

2022-09-28 06:19 UTC, catadarjan-tapptitude commented on app/src/main/java/com/internship/move/data/dto/UsersApiResponses.kt
> +    fun toUser(): User{
Also, this method seems to be unused

2022-09-28 06:19 UTC, catadarjan-tapptitude commented on app/src/main/java/com/internship/move/data/dto/UsersApiResponses.kt
> +    fun toUser() = User(name, email, UserStatus.fromString(status), drivingLicense != null)
Set the returntype of this method `fun toUser(): User` 
This way the compiler will know exactly what it is and does.
For example, as it is now if you try to write user.toUser().copy() it will work, but the compiler will now know to suggest you to copy method

2022-09-28 06:19 UTC, catadarjan-tapptitude commented on app/src/main/java/com/internship/move/data/dto/UsersApiResponses.kt
> +        user.numberOfTrips = numberOfTrips
If you still use this toUser method, I suggest taking advantage of the data class copy method like so:
`fun toUser(): User = user.toUser().copy(numberOfTrips = numberOfTrips)`

Also, numberOfTrips and scooters in the User data class should be immutable

2022-09-28 06:19 UTC, catadarjan-tapptitude commented on app/src/main/java/com/internship/move/ui/authentication/AuthenticationViewModel.kt
> +    val user: MutableLiveData<User> = MutableLiveData()
I suggest using backing fields when adding new MutableLiveData or tweaking old ones.
No need to refactor all of them, just change them whenever you interact with them again. I've seen the new ones are added correctly 😁

2022-09-28 06:19 UTC, catadarjan-tapptitude commented on app/src/main/java/com/internship/move/ui/home/map/MapFragment.kt
> +                delay(60000)
Use static fields instead of magic numbers

2022-09-28 06:19 UTC, catadarjan-tapptitude commented on app/src/main/java/com/internship/move/ui/home/map/MapFragment.kt
> +            } else if (user.status == UserStatus.FREE) {
I suggest importing the enums individually by name. It makes the code cleaner and easier to read imo

2022-09-28 06:19 UTC, catadarjan-tapptitude commented on app/src/main/java/com/internship/move/ui/home/map/MapFragment.kt
> +                delay(60000)
Same for the `displayCurrentLocation` & `createLocationRequest` methods

2022-09-28 06:19 UTC, catadarjan-tapptitude commented on app/src/main/java/com/internship/move/ui/home/unlock/UnlockFragment.kt
> +                    Toast.makeText(requireContext(), "Camera permission denied", Toast.LENGTH_LONG).show()
How come you're not using the alerter lib?

2022-09-28 06:19 UTC, catadarjan-tapptitude commented on app/src/main/java/com/internship/move/ui/home/unlock/UnlockFragment.kt
> +                if (result) {
I suggest renaming this to something more suggestive

2022-09-28 06:19 UTC, catadarjan-tapptitude commented on app/src/main/java/com/internship/move/ui/home/unlock/UnlockFragment.kt
> +            }.launch(Manifest.permission.CAMERA)
I suggest importing `CAMERA` constant directly to make the code cleaner

2022-09-28 06:19 UTC, catadarjan-tapptitude commented on app/src/main/java/com/internship/move/ui/home/unlock/UnlockFragment.kt
> +            UnlockMethod.QR -> checkCameraPermission()
I suggest importing the enums individually by name to make the code cleaner

2022-09-28 06:19 UTC, catadarjan-tapptitude commented on app/src/main/java/com/internship/move/ui/home/unlock/UnlockFragment.kt
> +                    delay(2000)
Extract to static field

2022-09-28 06:19 UTC, catadarjan-tapptitude commented on app/src/main/java/com/internship/move/ui/home/unlock/UnlockFragment.kt
> +            if (it == true) {
I'd name this lambda variable to something suggestive like `isUnlockSuccessful` 😁 
I also suggest renaming the (mutable)liveData fields to `unlockResult` or something like that 🤔

2022-09-28 06:19 UTC, catadarjan-tapptitude commented on app/src/main/java/com/internship/move/ui/home/unlock/UnlockFragment.kt
> +        binding.progressBar.isVisible = false
I think you could use a Group for these instead of setting them individually
https://developer.android.com/reference/androidx/constraintlayout/widget/Group

2022-09-28 06:19 UTC, catadarjan-tapptitude commented on app/src/main/res/layout/fragment_map.xml
> +            android:layout_marginBottom="4dp"
Extract raw dimens and use specific colors

2022-09-28 06:19 UTC, catadarjan-tapptitude commented on app/src/main/res/layout/fragment_menu.xml
> +        app:layout_constraintGuide_begin="30dp" />
Extract raw dimens

2022-09-28 06:19 UTC, catadarjan-tapptitude commented on app/src/main/res/layout/fragment_menu.xml
> +        app:layout_constraintTop_toBottomOf="@+id/generalSettingsTV" />
Use `@id/` to reference ids

2022-09-29 07:58 UTC, tapp-hadaralex approved these changes
Before merging, try to fix the `var` in the user class.

With data classes, have `val` as much as possible and use `copy` when needed

2022-09-29 07:58 UTC, tapp-hadaralex commented on app/src/main/java/com/internship/move/data/model/User.kt
> +    var scooter: Scooter? = null
Try to avoid `var` as much as possible. When needed, use the `.copy` value.

2022-09-29 07:58 UTC, tapp-hadaralex commented on app/src/main/res/layout/fragment_menu.xml
> +        style="@style/Heading5"
nice use of styling

2022-09-29 08:09 UTC, merged